/* This file is automatically generated with "make include/build_env.h". DO NOT EDIT */

#ifndef _BUILD_ENV_H
#define _BUILD_ENV_H

#define BUILD_ENV_UNAME "Linux alex-VirtualBox 3.11.0-15-generic #25~precise1-Ubuntu SMP Thu Jan 30 17:42:40 UTC 2014 i686 i686 i386 GNU/Linux"
#define BUILD_ENV_DATE "Вс. дек. 11 14:57:18 YAKT 2022"
#define BUILD_ENV_SRCDIR "/home/alex/n14u/dsl-n14u_gpl/apps/public/samba-3.5.8/source3"
#define BUILD_ENV_BUILDDIR "/home/alex/n14u/dsl-n14u_gpl/apps/public/samba-3.5.8/source3"
#define BUILD_ENV_USER "alex"
#define BUILD_ENV_HOST "alex-VirtualBox"
#define BUILD_ENV_COMPILER "mips-linux-uclibc-gcc"
#endif /* _BUILD_ENV_H */
