#ifndef MK1MF_BUILD
    /* auto-generated by util/mkbuildinf.pl for crypto/cversion.c */
    #define CFLAGS cflags
    /*
     * Generate CFLAGS as an array of individual characters. This is a
     * workaround for the situation where CFLAGS gets too long for a C90 string
     * literal
     */
    static const char cflags[] = {
        'c','o','m','p','i','l','e','r',':',' ','m','i','p','s','-','l','i','n',
        'u','x','-','u','c','l','i','b','c','-','g','c','c',' ','-','m','i','p',
        's','3','2','r','2',' ','-','m','s','o','f','t','-','f','l','o','a','t',
        ' ','-','I','.',' ','-','I','.','.',' ','-','I','.','.','/','i','n','c',
        'l','u','d','e',' ',' ','-','f','P','I','C',' ','-','D','O','P','E','N',
        'S','S','L','_','P','I','C',' ','-','D','O','P','E','N','S','S','L','_',
        'T','H','R','E','A','D','S',' ','-','D','_','R','E','E','N','T','R','A',
        'N','T',' ','-','D','D','S','O','_','D','L','F','C','N',' ','-','D','H',
        'A','V','E','_','D','L','F','C','N','_','H',' ','-','f','f','u','n','c',
        't','i','o','n','-','s','e','c','t','i','o','n','s',' ','-','f','d','a',
        't','a','-','s','e','c','t','i','o','n','s',' ','-','m','i','p','s','2',
        ' ','-','m','a','b','i','=','3','2',' ','-','O','3',' ','-','W','a','l',
        'l',' ','-','D','B','N','_','D','I','V','3','W',' ','-','D','O','P','E',
        'N','S','S','L','_','B','N','_','A','S','M','_','M','O','N','T',' ','-',
        'D','S','H','A','1','_','A','S','M',' ','-','D','S','H','A','2','5','6',
        '_','A','S','M',' ','-','D','A','E','S','_','A','S','M','\0'
    };
    #define PLATFORM "platform: linux-mips32"
    #define DATE "built on: Sun Dec 11 14:47:05 2022"
#endif
